from __future__ import annotations

import json
from html import escape
from pathlib import Path

from .models import DailyReport, RankedRepo, RawReport, RawRepo


def write_outputs(report: DailyReport, root: Path) -> None:
    data_dir = root / "data"
    reports_dir = root / "reports"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    payload = report.to_dict()
    daily_json = data_dir / f"{report.date}.json"
    latest_json = data_dir / "latest.json"
    daily_markdown = reports_dir / f"{report.date}.md"

    json_text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    daily_json.write_text(json_text, encoding="utf-8")
    latest_json.write_text(json_text, encoding="utf-8")
    daily_markdown.write_text(render_daily_markdown(report), encoding="utf-8")
    (root / "README.md").write_text(render_readme(report), encoding="utf-8")


def write_raw_outputs(report: RawReport, root: Path) -> None:
    data_dir = root / "data" / "raw"
    reports_dir = root / "reports" / "raw"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    payload = report.to_dict()
    json_text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    (data_dir / f"{report.date}.json").write_text(json_text, encoding="utf-8")
    (data_dir / "latest.json").write_text(json_text, encoding="utf-8")
    (reports_dir / f"{report.date}.md").write_text(render_raw_markdown(report), encoding="utf-8")


def render_readme(report: DailyReport) -> str:
    return "\n".join(
        [
            "# GitHub AI Daily Rising Stars",
            "",
            "> 自动统计北京时间昨日 GitHub 新增 stars 最快的 AI 相关开源项目，并用中文解释项目作用与潜在应用场景。",
            "",
            f"## 最新榜单：{report.date} ({report.timezone})",
            "",
            _render_table(report.items),
            "",
            "## 数据与归档",
            "",
            f"- JSON 数据：[data/{report.date}.json](data/{report.date}.json)",
            f"- Markdown 归档：[reports/{report.date}.md](reports/{report.date}.md)",
            "- 最新 JSON：[data/latest.json](data/latest.json)",
            "",
            "## 自动更新",
            "",
            "GitHub Actions 每天多次检查并生成兜底中文解析；Codex 定时任务可在网络可用时覆盖为更高质量解析。",
            "",
            "<!-- generated by gitpopular -->",
            "",
        ]
    )


def render_daily_markdown(report: DailyReport) -> str:
    return "\n".join(
        [
            f"# GitHub AI Rising Stars - {report.date}",
            "",
            f"- 时区：`{report.timezone}`",
            f"- 生成时间：`{report.generated_at}`",
            f"- 数据源：GH Archive WatchEvent、GitHub REST API、{report.source.get('analysis', '未知分析')}",
            "",
            "## 社媒速读版",
            "",
            "```text",
            _render_social_digest(report),
            "```",
            "",
            _render_table(report.items),
            "",
            _render_project_cards(report.items),
            "",
        ]
    )


def render_raw_markdown(report: RawReport) -> str:
    return "\n".join(
        [
            f"# Raw GitHub AI Rising Stars - {report.date}",
            "",
            f"- 时区：`{report.timezone}`",
            f"- 生成时间：`{report.generated_at}`",
            "- 数据源：GH Archive WatchEvent、GitHub REST API",
            "- 说明：该文件只包含免费采集的原始榜单和 README，最终中文报告由 GitHub Actions 兜底生成，Codex 可稍后增强。",
            "",
            _render_raw_table(report.items),
            "",
        ]
    )


def _render_table(items: list[RankedRepo]) -> str:
    lines = [
        "| 排名 | 项目 | 一句话亮点 | 昨日新增 stars | 当前 stars | 语言 | 标签 | 推荐 | 接入 |",
        "| --- | --- | --- | ---: | ---: | --- | --- | ---: | --- |",
    ]
    for item in items:
        lines.append(
            "| "
            f"{item.rank} | "
            f"[{_escape_md(item.repo)}]({item.url}) | "
            f"{_escape_md(_display_highlight(item))} | "
            f"{_format_int(item.yesterday_new_stars)} | "
            f"{_format_int(item.total_stars)} | "
            f"{_escape_md(item.language or '未知')} | "
            f"{_render_inline_tags(item.project_tags_zh)} | "
            f"{_score_stars(item.recommendation_score)} | "
            f"{_escape_md(item.adoption_difficulty)} |"
        )
    return "\n".join(lines)


def _render_raw_table(items: list[RawRepo]) -> str:
    lines = [
        "| 排名 | 项目 | 昨日新增 stars | 当前 stars | 语言 | README |",
        "| --- | --- | ---: | ---: | --- | --- |",
    ]
    for item in items:
        lines.append(
            "| "
            f"{item.rank} | "
            f"[{_escape_md(item.repo)}]({item.url}) | "
            f"{_format_int(item.yesterday_new_stars)} | "
            f"{_format_int(item.total_stars)} | "
            f"{_escape_md(item.language or '未知')} | "
            f"[README]({item.readme_url}) |"
        )
    return "\n".join(lines)


def _render_project_cards(items: list[RankedRepo]) -> str:
    sections: list[str] = []
    for item in items:
        scenarios = "\n".join(
            f"{index}. {scenario}" for index, scenario in enumerate(item.application_scenarios_zh, start=1)
        )
        adoption_notes = item.adoption_notes_zh or [
            "先阅读 README 和示例，确认项目是否覆盖当前使用场景。",
            "检查许可证、更新频率和 issue 状态，再决定是否引入生产流程。",
            "优先搭建小规模原型，验证依赖、部署和集成成本。",
        ]
        notes = "\n".join(f"{index}. {note}" for index, note in enumerate(adoption_notes, start=1))
        topics = ", ".join(f"`{topic}`" for topic in item.topics) if item.topics else "无"
        target_users = "、".join(item.target_users_zh) if item.target_users_zh else "AI 工具调研者、开发者"
        sections.append(
            "\n".join(
                [
                    "---",
                    "",
                    "<details open>",
                    f"<summary><strong>#{item.rank} "
                    f"<a href=\"{escape(item.url, quote=True)}\">{escape(item.repo)}</a></strong> "
                    f"· +{_format_int(item.yesterday_new_stars)} stars · "
                    f"{escape(item.language or '未知')}</summary>",
                    "",
                    "| 指标 | 内容 |",
                    "| --- | --- |",
                    f"| 项目类别 | `{_escape_md(item.category_zh or 'AI 工具')}` |",
                    f"| 一句话定位 | {_escape_md(item.positioning_zh or item.purpose_zh)} |",
                    f"| 一句话亮点 | {_escape_md(_display_highlight(item))} |",
                    f"| 适合人群 | {_escape_md(target_users)} |",
                    f"| 最佳使用场景 | {_escape_md(item.best_use_case_zh or _first_or_default(item.application_scenarios_zh))} |",
                    f"| 不适合场景 | {_escape_md(item.not_suitable_zh or '不适合在未验证依赖、许可证和维护状态前直接投入生产。')} |",
                    f"| 项目标签 | {_render_inline_tags(item.project_tags_zh)} |",
                    f"| 推荐关注 | {_score_stars(item.recommendation_score)} |",
                    f"| 成熟度 | {_score_stars(item.maturity_score)} |",
                    f"| 接入难度 | `{_escape_md(item.adoption_difficulty)}` |",
                    f"| AI 置信度 | `{item.ai_confidence:.2f}` |",
                    f"| 当前 stars | `{_format_int(item.total_stars)}` |",
                    f"| Topics | {topics} |",
                    f"| README | [{_escape_md(item.readme_url)}]({item.readme_url}) |",
                    "",
                    "#### 产品/应用价值",
                    "",
                    item.product_view_zh or item.purpose_zh,
                    "",
                    "#### 技术选型观察",
                    "",
                    item.technical_view_zh or item.summary_zh,
                    "",
                    "#### 趋势判断",
                    "",
                    item.trend_view_zh or item.summary_zh,
                    "",
                    "#### 应用场景预测",
                    "",
                    scenarios,
                    "",
                    "#### 采用建议",
                    "",
                    notes,
                    "",
                    "</details>",
                ]
            )
        )
    return "\n\n".join(sections)


def _render_social_digest(report: DailyReport) -> str:
    lines = [f"GitHub AI 热门项目速读（{report.date}）"]
    for item in report.items:
        repo_name = item.repo.split("/")[-1]
        lines.extend(
            [
                f"👉{item.rank:02d} {repo_name} ⭐ {_format_short_stars(item.total_stars)} · {item.language or '未知'}",
                _display_highlight(item),
                f"🔗 github.com/{item.repo}",
            ]
        )
    lines.append("#AI工具 #开源工具 #GitHub #大模型 #个人开发者")
    return "\n".join(lines)


def _display_highlight(item: RankedRepo) -> str:
    return item.highlight_zh or item.positioning_zh or item.purpose_zh


def _first_or_default(items: list[str]) -> str:
    return items[0] if items else "先搭建最小原型，验证它是否适配当前工作流。"


def _escape_md(value: str) -> str:
    return value.replace("|", "\\|")


def _format_int(value: int) -> str:
    return f"{value:,}"


def _format_short_stars(value: int) -> str:
    if value >= 1000:
        return f"{value / 1000:.1f}k"
    return str(value)


def _render_inline_tags(tags: list[str]) -> str:
    if not tags:
        return "`AI 工具`"
    return " ".join(f"`{_escape_md(tag)}`" for tag in tags[:5])


def _score_stars(score: int) -> str:
    normalized = max(1, min(int(score), 5))
    return "★" * normalized + "☆" * (5 - normalized)
