from __future__ import annotations

import json
from pathlib import Path

from .models import DailyReport, RankedRepo, RawReport, RawRepo


def write_outputs(report: DailyReport, root: Path) -> None:
    data_dir = root / "data"
    reports_dir = root / "reports"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    payload = report.to_dict()
    daily_json = data_dir / f"{report.date}.json"
    latest_json = data_dir / "latest.json"
    daily_markdown = reports_dir / f"{report.date}.md"

    json_text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    daily_json.write_text(json_text, encoding="utf-8")
    latest_json.write_text(json_text, encoding="utf-8")
    daily_markdown.write_text(render_daily_markdown(report), encoding="utf-8")
    (root / "README.md").write_text(render_readme(report), encoding="utf-8")


def write_raw_outputs(report: RawReport, root: Path) -> None:
    data_dir = root / "data" / "raw"
    reports_dir = root / "reports" / "raw"
    data_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)

    payload = report.to_dict()
    json_text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    (data_dir / f"{report.date}.json").write_text(json_text, encoding="utf-8")
    (data_dir / "latest.json").write_text(json_text, encoding="utf-8")
    (reports_dir / f"{report.date}.md").write_text(render_raw_markdown(report), encoding="utf-8")


def render_readme(report: DailyReport) -> str:
    return "\n".join(
        [
            "# GitHub AI Daily Rising Stars",
            "",
            "> 自动统计北京时间昨日 GitHub 新增 stars 最快的 AI 相关开源项目，并用中文解释项目作用与潜在应用场景。",
            "",
            f"## 最新榜单：{report.date} ({report.timezone})",
            "",
            _render_table(report.items),
            "",
            _render_project_sections(report.items),
            "",
            "## 数据与归档",
            "",
            f"- JSON 数据：[data/{report.date}.json](data/{report.date}.json)",
            f"- Markdown 归档：[reports/{report.date}.md](reports/{report.date}.md)",
            "- 最新 JSON：[data/latest.json](data/latest.json)",
            "",
            "## 自动更新",
            "",
            "GitHub Actions 每天多次检查并生成兜底中文解析；Codex 定时任务可在网络可用时覆盖为更高质量解析。",
            "",
            "<!-- generated by gitpopular -->",
            "",
        ]
    )


def render_daily_markdown(report: DailyReport) -> str:
    return "\n".join(
        [
            f"# GitHub AI Rising Stars - {report.date}",
            "",
            f"- 时区：`{report.timezone}`",
            f"- 生成时间：`{report.generated_at}`",
            f"- 数据源：GH Archive WatchEvent、GitHub REST API、{report.source.get('analysis', '未知分析')}",
            "",
            _render_table(report.items),
            "",
            _render_project_sections(report.items),
            "",
        ]
    )


def render_raw_markdown(report: RawReport) -> str:
    return "\n".join(
        [
            f"# Raw GitHub AI Rising Stars - {report.date}",
            "",
            f"- 时区：`{report.timezone}`",
            f"- 生成时间：`{report.generated_at}`",
            "- 数据源：GH Archive WatchEvent、GitHub REST API",
            "- 说明：该文件只包含免费采集的原始榜单和 README，最终中文报告由 GitHub Actions 兜底生成，Codex 可稍后增强。",
            "",
            _render_raw_table(report.items),
            "",
        ]
    )


def _render_table(items: list[RankedRepo]) -> str:
    lines = [
        "| 排名 | 项目 | 昨日新增 stars | 当前 stars | 语言 | AI 置信度 |",
        "| --- | --- | ---: | ---: | --- | ---: |",
    ]
    for item in items:
        lines.append(
            "| "
            f"{item.rank} | "
            f"[{_escape_md(item.repo)}]({item.url}) | "
            f"{_format_int(item.yesterday_new_stars)} | "
            f"{_format_int(item.total_stars)} | "
            f"{_escape_md(item.language or '未知')} | "
            f"{item.ai_confidence:.2f} |"
        )
    return "\n".join(lines)


def _render_raw_table(items: list[RawRepo]) -> str:
    lines = [
        "| 排名 | 项目 | 昨日新增 stars | 当前 stars | 语言 | README |",
        "| --- | --- | ---: | ---: | --- | --- |",
    ]
    for item in items:
        lines.append(
            "| "
            f"{item.rank} | "
            f"[{_escape_md(item.repo)}]({item.url}) | "
            f"{_format_int(item.yesterday_new_stars)} | "
            f"{_format_int(item.total_stars)} | "
            f"{_escape_md(item.language or '未知')} | "
            f"[README]({item.readme_url}) |"
        )
    return "\n".join(lines)


def _render_project_sections(items: list[RankedRepo]) -> str:
    sections: list[str] = []
    for item in items:
        scenarios = "\n".join(
            f"{index}. {scenario}" for index, scenario in enumerate(item.application_scenarios_zh, start=1)
        )
        topics = ", ".join(f"`{topic}`" for topic in item.topics) if item.topics else "无"
        sections.append(
            "\n".join(
                [
                    f"### {item.rank}. [{_escape_md(item.repo)}]({item.url})",
                    "",
                    f"- 昨日新增 stars：`{_format_int(item.yesterday_new_stars)}`",
                    f"- 当前 stars：`{_format_int(item.total_stars)}`",
                    f"- 主要语言：`{item.language or '未知'}`",
                    f"- Topics：{topics}",
                    f"- README：[{_escape_md(item.readme_url)}]({item.readme_url})",
                    "",
                    f"**项目作用**：{item.purpose_zh}",
                    "",
                    f"**简要解析**：{item.summary_zh}",
                    "",
                    "**应用场景预测**：",
                    "",
                    scenarios,
                ]
            )
        )
    return "\n\n".join(sections)


def _escape_md(value: str) -> str:
    return value.replace("|", "\\|")


def _format_int(value: int) -> str:
    return f"{value:,}"
